# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: fedora/python-fedorainfra-ansible-messages.spec

# add or remove files that should be synced
synced_files:
    - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: fedorainfra-ansible-messages
# downstream (Fedora) RPM package name
downstream_package_name: python-fedorainfra_ansible_messages

actions:
  create-archive:
    - python3 setup.py sdist --dist-dir ./fedora/
    - bash -c "ls -1t ./fedora/*.tar.gz | head -n 1"
  get-current-version: python3 setup.py --version
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - epel-8
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - epel-8
  - job: copr_build
    trigger: commit
    metadata:
      branch: master
      targets:
        - epel-8
      project: wip-fedorainfra-ansible-messages
      list_on_homepage: False
      preserve_project: False

